export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS ";
export const GET_ALL_PRODUCTS_PAGANATION = "GET_ALL_PRODUCTS_PAGANATION ";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT ";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS ";
export const GET_ALL_USERS = "GET_ALL_USERS ";

